name: "Cušpajz"
id: "cuspajz"

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://cuspajz.com/tekstovi-pjesama/pjesma/{artist}/{title}.html"
    pattern: ['<p\\sclass="text\\sclearfix">\\s*(?<lyrics>.*?)</p>', s]
    
post-filters:
- strip_html
- entity_decode