name: "Letras de músicas"
id: "letras.mus.br"

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://letras.mus.br/{artist}/{title}/"
    pattern: ['<div id="div_letra"[^>]*>(?<lyrics>.*?)</div>', s]
    
post-filters:
- p2break
- strip_html
- clean_spaces
- utf8_encode