name: "metrolyrics.com"

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://www.metrolyrics.com/{title}-lyrics-{artist}.html"
    pattern: ['<div id="lyrics-body">(?<lyrics>.*?)</div>', s]
    
post-filters:
- strip_html
- strip_links
- entity_decode
- clean_spaces
- utf8_encode