name: Oldies Lyrics
id: oldielyrics

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, _]
    title:
        type: title
        filters: artist

config:
    url: "http://oldielyrics.com/lyrics/{artist}/{title}.html"
    pattern: ['<div\\s+class="lyrics"[^>]*>\\s*<p>(?<lyrics>.+)</p>\\s*</div>', s]
    
post-filters:
- strip_html
- strip_links
- entity_decode
- clean_spaces
- utf8_encode