name: "plyrics.com"

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - strip_nonascii
    title:
        type: title
        filters: artist

config:
    url: "http://www.plyrics.com/lyrics/{artist}/{title}.html"
    pattern: ['<div id="lyrics-body">(?<lyrics>.*?)</div>', s]
    
post-filters:
- strip_html
- utf8_encode
