name: Smriti

variables:
    title:
        type: title
        filters:
        - [strip_nonascii, -]

config:
    url: "http://smriti.com/hindi-songs/{title}"
    pattern: ['<div class="songbody">(?<lyrics>.*?)</div>', s]
    
post-filters:
- br2nl
- strip_html
- trim
- utf8_encode