name: "metrolyrics.com"

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://www.songlyrics.com/{artist}/{title}-lyrics/"
    pattern: ['<div id="songLyricsDiv-outer">(?<lyrics>.*?)</div>', s]
    
post-filters:
- strip_html
- entity_decode
- clean_spaces
- utf8_encode