name: Tekstovi Pjesama

variables:
    artist:
        type: artist
        filters:
        - diacritics2ascii
        - lowercase
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://tekstovipjesama.com/{artist}/{title}"
    pattern: ['<div\s+class="entry"[^>]*>\s*<div[^>]*>\s*(?<lyrics>.*?)</div>', s]
    
post-filters:
- p2break
- strip_html
- utf8_encode
- clean_spaces