name: Tekstowo

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, _]
    title:
        type: title
        filters: artist

config:
    url: "http://www.tekstowo.pl/piosenka,{artist},{title}.html"
    pattern: ['<div\\s+class="song-text"[^>]*>(?<lyrics>.*?)<p>&nbsp;</p>', s]
    
post-filters:
- strip_html
- utf8_encode