name: "tekstovipjesama.com"

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - [strip_nonascii, -]
    title:
        type: title
        filters: artist

config:
    url: "http://tekstovipjesama.com/{artist}/{title}"
    pattern: ['<div\\s+class="entry"[^>]*>\\s*<div[^>]*>\\s*(?<lyrics>.*?)</div>', s]
    
post-filters:
- p2break
- br2nl
- strip_html
- entity_decode
- utf8_encode