name: "urbanlyrics.com"
url: "http://www.urbanlyrics.com/lyrics/{artist:lower,alpha}/{title:lower,alpha}.html"
    
expressions:
- '<!-- start of lyrics -->(?<lyrics>.+?)<!-- end of lyrics -->'
    
filters:
- strip_html
- utf8_encode