name: Urban Lyrics

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - strip_nonascii
    title:
        type: title
        filters: artist

config:
    url: "http://www.urbanlyrics.com/lyrics/{artist}/{title}.html"
    pattern: ['<!-- start of lyrics -->(?<lyrics>.+?)<!-- end of lyrics -->', s]
    
post-filters:
- strip_html
- utf8_encode